name: i501
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipykernel
    - spacy
    - scattertext
    - pandas
    - scikit-learn
    - nltk
    - networkx
    - corextopic
    - scipy
    - matplotlib
    - seaborn
    - vaderSentiment
    - ipywidgets